# build.yml

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build HTML with secrets
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          # sed 명령의 경로를 루트 폴더로 변경
          sed -i "s|APP_KEY|'${APP_KEY}'|g" index.html
          sed -i "s|APP_SECRET|'${APP_SECRET}'|g" index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-html
          # 아티팩트 업로드 경로를 루트 폴더로 변경
          path: index.html
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # index.html이 바로 루트에 있으므로 './'를 사용
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
