name: Build and Deploy

on:
  push:
    branches:
      - main # 또는 배포하려는 브랜치

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Node.js 버전을 설정하세요.

      - name: Install dependencies
        run: npm install # 필요한 경우 의존성을 설치합니다.

      - name: Build HTML with secrets
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          # sed 명령어를 사용하여 HTML 파일의 플레이스홀더를 실제 secret 값으로 치환합니다.
          # HTML 파일 내에서 와 같이 표시하고,
          # sed로 해당 부분을 치환하도록 설정합니다.
          sed -i "s/APP_KEY_PLACEHOLDER/$APP_KEY/g" index.html
          sed -i "s/APP_SECRET_PLACEHOLDER/$APP_SECRET/g" index.html
          # 다른 secret 값들도 동일한 방식으로 처리할 수 있습니다.

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-html
          path: index.html # 빌드된 HTML 파일 경로

      # 필요에 따라 GitHub Pages, S3 등으로 배포하는 단계를 추가할 수 있습니다.
